using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace TheBlackBox;

/// <summary>
/// The Black Box: the title screen, the save form, and the table. Owns the box and the sprite batches.
/// </summary>
/// <remarks>
/// The box is on every screen, so it lives here and each screen moves it where it wants it.
/// The run itself is TableScreen; this decides which screen is in front and draws the batches.
/// </remarks>
public partial class BlackBoxGame : Game
{
    internal const int ScreenWidth = 1600;
    internal const int ScreenHeight = 900;

    /// <summary>Where the box hangs on the title screen.</summary>
    private const float BoxCenterY = 500f;

    /// <summary>How much ash is caught in the pull at any one time.</summary>
    private const int AshCount = 34;

    private const float TitleY = 56f;
    private const float EscapeHintY = 856f;

    private const string Title = "The Black Box";
    private const string StartLabel = "START GAME";
    private const string ExitLabel = "EXIT";

    /// <summary>Centre line of the row of buttons, clear of the bottom of the box, and the gap between the two.</summary>
    private const float ButtonRowY = 806f;
    private const float ButtonGap = 36f;

    // The title gets a tight deep red shadow instead of black. The serif is light, and anything wider ghosts around the strokes.
    private static readonly Color TitleColor = new(240, 235, 240);
    private static readonly Color TitleShadow = new(104, 12, 17);
    private static readonly Color HintColor = new(150, 140, 142);

    /// <summary>Not quite black, so the box itself still reads as the darkest thing on screen.</summary>
    private static readonly Color VoidColor = new(10, 8, 16);

    /// <summary>Additive blending for premultiplied-alpha content. In this case this is for the eye glow.</summary>
    /// <remarks>
    /// The stock BlendState.Additive multiplies by alpha again on the way in, which the pipeline
    /// already did, so the glow came out dim. Forcing the source factor to One fixes it.
    ///
    /// Author Note for Grader: This code was developed and generated by AI. It is intended to handle additive blending
    ///  correctly for premultiplied-alpha content. (the Eye Glow) Thank you for understanding! -Caleb (Pretty cool too!)
    /// </remarks>
    private static readonly BlendState PremultipliedAdditive = new()
    {
        ColorSourceBlend = Blend.One,
        AlphaSourceBlend = Blend.One,
        ColorDestinationBlend = Blend.One,
        AlphaDestinationBlend = Blend.One,
    };

    private GraphicsDeviceManager _graphics;
    private SpriteBatch _spriteBatch;

    private AshDriftSprite[] _ashDrift;
    private BlackBoxSprite _blackBox;
    private AshSprite[] _ashes;

    private ButtonSprite _startButton;
    private ButtonSprite _exitButton;

    private SaveSlotMenu _slotMenu;
    private NameEntry _nameEntry;
    private TableScreen _table;

    private SpriteFont _titleFont;
    private SpriteFont _uiFont;

    private Screen _screen = Screen.Title;

    /// <summary>The run waiting on a name, and the slot it will go back into.</summary>
    private SaveData _namingRun;
    private int _namingSlot;

    private KeyboardState _lastKeyboard;

    public BlackBoxGame()
    {
        _graphics = new GraphicsDeviceManager(this);
        _graphics.PreferredBackBufferWidth = ScreenWidth;
        _graphics.PreferredBackBufferHeight = ScreenHeight;
        _graphics.ApplyChanges();
        Content.RootDirectory = "Content";

        // The eyes follow the cursor, so the player needs to be able to see it.
        IsMouseVisible = true;
    }

    protected override void Initialize()
    {
        // Initialize the ash drift layers and the black box before the game starts.
        _ashDrift = new AshDriftSprite[]
        {
            new(new Vector2(7f, 3f), new Color(150, 146, 150) * 0.55f, Layers.AshDriftFar),
            new(new Vector2(-16f, 7f), new Color(214, 196, 180) * 0.75f, Layers.AshDriftNear),
        };

        _blackBox = new BlackBoxSprite()
        {
            Position = new Vector2(ScreenWidth / 2f, BoxCenterY),
        };

        // Loose ash caught in whatever the box is doing to the air around it.
        _ashes = new AshSprite[AshCount];
        for (int i = 0; i < _ashes.Length; i++)
        {
            _ashes[i] = new AshSprite { Center = _blackBox.Position };
        }

        // Amber is the box making an offer; red is saved for the choice that ends things.
        _startButton = new ButtonSprite(StartLabel, new Vector2(ScreenWidth / 2f, ButtonRowY), ButtonSprite.Amber);
        _exitButton = new ButtonSprite(ExitLabel, new Vector2(ScreenWidth / 2f, ButtonRowY), ButtonSprite.EmberRed);

        _startButton.Clicked += OpenSlotMenu;
        _exitButton.Clicked += Exit;

        _slotMenu = new SaveSlotMenu(new Rectangle(0, 0, ScreenWidth, ScreenHeight));
        _slotMenu.SlotChosen += BeginRun;
        _slotMenu.Closed += ShowTitle;

        _nameEntry = new NameEntry(new Rectangle(0, 0, ScreenWidth, ScreenHeight));
        _nameEntry.Confirmed += NameRun;
        _nameEntry.Cancelled += OpenSlotMenu;

        _table = new TableScreen(_blackBox);
        _table.Left += ShowTitle;

        // Characters come from the window, so the form never has to deal with layouts or shift.
        Window.TextInput += (_, e) => _nameEntry.TypeCharacter(e.Character);

        base.Initialize();
    }

    protected override void LoadContent()
    {
        _spriteBatch = new SpriteBatch(GraphicsDevice);

        _titleFont = Content.Load<SpriteFont>("spectral-title");
        _uiFont = Content.Load<SpriteFont>("spectral-ui");

        foreach (var layer in _ashDrift) layer.LoadContent(Content);
        _blackBox.LoadContent(Content);
        foreach (var mote in _ashes) mote.LoadContent(Content);

        _startButton.LoadContent(Content);
        _exitButton.LoadContent(Content);
        LayOutButtons();

        _slotMenu.LoadContent(Content, GraphicsDevice);
        _nameEntry.LoadContent(Content, GraphicsDevice);
        _table.LoadContent(Content, GraphicsDevice);
    }

    /// <summary>Centres the row of buttons on screen.</summary>
    /// <remarks>Has to run after LoadContent, since a button does not know its width until it has measured its label.</remarks>
    private void LayOutButtons()
    {
        float total = _startButton.Size.X + ButtonGap + _exitButton.Size.X;
        float left = (ScreenWidth - total) / 2f;

        _startButton.Center = new Vector2(left + _startButton.Size.X / 2f, ButtonRowY);
        _exitButton.Center = new Vector2(
            left + _startButton.Size.X + ButtonGap + _exitButton.Size.X / 2f,
            ButtonRowY);
    }

    protected override void Update(GameTime gameTime)
    {
        KeyboardState keyboard = Keyboard.GetState();

        // On the edge, not while held, or one press would back out of the form and then close the game.
        if (keyboard.IsKeyDown(Keys.Escape) && _lastKeyboard.IsKeyUp(Keys.Escape))
            Back();

        _lastKeyboard = keyboard;

        UpdateProof();

        // The box keeps running whatever screen is on top of it, and the ash follows it wherever a screen has put it.
        foreach (var layer in _ashDrift) layer.Update(gameTime);
        _blackBox.Update(gameTime, GraphicsDevice.Viewport);
        foreach (var mote in _ashes)
        {
            mote.Center = _blackBox.Position;
            mote.Update(gameTime);
        }

        // Only the screen in front takes input, so a click on the form does not also hit START underneath.
        switch (_screen)
        {
            case Screen.Title:
                _startButton.Update(gameTime);
                _exitButton.Update(gameTime);
                break;

            case Screen.SlotSelect:
                _slotMenu.Update(gameTime);
                break;

            case Screen.NameEntry:
                _nameEntry.Update(gameTime);
                break;

            case Screen.Run:
                _table.Update(gameTime);
                break;
        }

        base.Update(gameTime);
    }

    protected override void Draw(GameTime gameTime)
    {
        BeginProofCapture();
        GraphicsDevice.Clear(VoidColor);

        bool onTable = _screen == Screen.Run;

        // 1. Everything the eye light falls on: the sky (or the room) and the box. Point sampling keeps the pixel art crisp.
        _spriteBatch.Begin(SpriteSortMode.BackToFront, BlendState.AlphaBlend, SamplerState.PointClamp);

        // The room replaces the drifting ash sky on the table, until the close-up takes the room away again.
        if (onTable && !_table.IsCloseUp) _table.DrawScene(_spriteBatch);
        else foreach (var layer in _ashDrift) layer.Draw(gameTime, _spriteBatch, GraphicsDevice.Viewport);

        _blackBox.DrawBody(gameTime, _spriteBatch);
        _spriteBatch.End();

        // 2. The eye glow, additive so the light spills onto the rim. Linear sampling so it stays soft.
        _spriteBatch.Begin(SpriteSortMode.BackToFront, PremultipliedAdditive, SamplerState.LinearClamp);
        _blackBox.DrawEyeGlow(gameTime, _spriteBatch);
        _spriteBatch.End();

        // 3. The eyes over the glow, the ash falling past in front of everything, and the table's hands over that.
        _spriteBatch.Begin(SpriteSortMode.BackToFront, BlendState.AlphaBlend, SamplerState.PointClamp);
        _blackBox.DrawEyes(gameTime, _spriteBatch);
        foreach (var mote in _ashes) mote.Draw(gameTime, _spriteBatch);
        if (onTable) _table.DrawFront(gameTime, _spriteBatch);
        _spriteBatch.End();

        // 4. Text, sampled linearly so the font stays smooth.
        _spriteBatch.Begin(SpriteSortMode.BackToFront, BlendState.AlphaBlend, SamplerState.LinearClamp);
        if (onTable) _table.DrawText(_spriteBatch);
        else DrawTitle();
        _spriteBatch.End();

        // 5. The plates. Point sampling because they are pixel art; the labels are 1:1 so they are fine under it.
        _spriteBatch.Begin(SpriteSortMode.BackToFront, BlendState.AlphaBlend, SamplerState.PointClamp);
        if (onTable)
        {
            _table.DrawPlates(gameTime, _spriteBatch);
        }
        else if (_screen == Screen.Title)
        {
            _startButton.Draw(gameTime, _spriteBatch);
            _exitButton.Draw(gameTime, _spriteBatch);
        }
        _spriteBatch.End();

        // 6. The forms, in their own batch so the veil covers everything above instead of sorting against one batch.
        _spriteBatch.Begin(SpriteSortMode.BackToFront, BlendState.AlphaBlend, SamplerState.PointClamp);
        _slotMenu.Draw(gameTime, _spriteBatch);
        _nameEntry.Draw(gameTime, _spriteBatch);
        _spriteBatch.End();

        EndProofCapture();
        base.Draw(gameTime);
    }

    /// <summary>Draws the title and the line under it, on every screen but the table.</summary>
    private void DrawTitle()
    {
        Text.DrawCentered(_spriteBatch, _titleFont, Title, TitleY, TitleColor, TitleShadow, Palette.ShadowOffset);

        // Escape is a shortcut, so it is stated once and quietly. What it does depends on the screen.
        string hint = _screen == Screen.Title ? "ESC" : "ESC  ·  BACK";
        Text.DrawCentered(_spriteBatch, _uiFont, hint, EscapeHintY, HintColor, Palette.Shadow, Palette.ShadowOffset);
    }

    /// <summary>Opens the save form over the title screen.</summary>
    private void OpenSlotMenu()
    {
        _screen = Screen.SlotSelect;
        _slotMenu.Open();
    }

    /// <summary>Takes the player into the run held in a slot.</summary>
    /// <param name="slot">Which slot it came out of, and goes back into.</param>
    /// <param name="run">The run.</param>
    private void BeginRun(int slot, SaveData run)
    {
        // No name yet means the run has not started, however many times the slot was opened.
        if (string.IsNullOrWhiteSpace(run.PlayerName))
        {
            _namingSlot = slot;
            _namingRun = run;
            _screen = Screen.NameEntry;
            _nameEntry.Open();
            return;
        }

        EnterRun(slot, run);
    }

    /// <summary>Takes the name the player gave and starts the run with it.</summary>
    /// <remarks>Saved right away so the name is never asked for twice. A failed write is shown on the table, not fatal.</remarks>
    /// <param name="name">What the player called themselves.</param>
    private void NameRun(string name)
    {
        _namingRun.PlayerName = name;

        string status = SaveSystem.Write(_namingSlot, _namingRun) ? null : TableScreen.SaveFailed + SaveSystem.LastError;
        EnterRun(_namingSlot, _namingRun, status);

        _namingRun = null;
    }

    /// <summary>Puts the table in front with a run on it.</summary>
    /// <param name="slot">Which slot the run goes back into.</param>
    /// <param name="run">The run.</param>
    /// <param name="status">Why a save just failed, or null.</param>
    private void EnterRun(int slot, SaveData run, string status = null)
    {
        _screen = Screen.Run;
        _table.Enter(slot, run, status);
    }

    /// <summary>Returns to the title screen, with both of its buttons cold again.</summary>
    private void ShowTitle()
    {
        _screen = Screen.Title;

        // The box goes back to owning the whole title screen.
        _blackBox.Position = new Vector2(ScreenWidth / 2f, BoxCenterY);
        _blackBox.Scale = BlackBoxSprite.DrawScale;

        // The buttons were frozen mid-animation under the form, so reset them.
        _startButton.Reset();
        _exitButton.Reset();
    }

    /// <summary>Backs out of whatever is in front: the form, then the run, then the game.</summary>
    private void Back()
    {
        switch (_screen)
        {
            case Screen.SlotSelect:
                _slotMenu.Close();
                break;

            case Screen.NameEntry:
                _nameEntry.Close();
                break;

            case Screen.Run:
                _table.Leave();
                break;

            default:
                Exit();
                break;
        }
    }
}
