using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;

namespace TheBlackBox;

/// <summary>
/// The box, the ash it pulls in, and the dead sky behind it. One of each for the whole game.
/// </summary>
/// <remarks>
/// This used to live in BlackBoxGame. Now that the screens are separate classes, it is a
/// component on its own so it keeps running whatever screen is up (the box never stops
/// looking around), and a service so the title and the table share the same box. Each screen
/// moves it where it wants it and draws the parts it needs.
/// </remarks>
public class BoxScene : GameComponent
{
    /// <summary>Where the box hangs on the title screen.</summary>
    private const float TitleBoxY = 500f;

    /// <summary>How much ash is caught in the pull at any one time.</summary>
    private const int AshCount = 34;

    /// <summary>Additive blending for premultiplied-alpha content. In this case this is for the eye glow.</summary>
    /// <remarks>
    /// The stock BlendState.Additive multiplies by alpha again on the way in, which the pipeline
    /// already did, so the glow came out dim. Forcing the source factor to One fixes it.
    ///
    /// Author Note for Grader: This code was developed and generated by AI. It is intended to handle additive blending
    ///  correctly for premultiplied-alpha content. (the Eye Glow) Thank you for understanding! -Caleb (Pretty cool too!)
    /// </remarks>
    public static readonly BlendState PremultipliedAdditive = new()
    {
        ColorSourceBlend = Blend.One,
        AlphaSourceBlend = Blend.One,
        ColorDestinationBlend = Blend.One,
        AlphaDestinationBlend = Blend.One,
    };

    private readonly AshDriftSprite[] _ashDrift;
    private readonly AshSprite[] _ashes;

    /// <summary>The box itself.</summary>
    public BlackBoxSprite Box { get; }

    /// <summary>Builds the box, the two layers of sky and the loose ash.</summary>
    /// <param name="game">The game it belongs to.</param>
    public BoxScene(Game game) : base(game)
    {
        _ashDrift = new AshDriftSprite[]
        {
            new(new Vector2(7f, 3f), new Color(150, 146, 150) * 0.55f, Layers.AshDriftFar),
            new(new Vector2(-16f, 7f), new Color(214, 196, 180) * 0.75f, Layers.AshDriftNear),
        };

        Box = new BlackBoxSprite();
        PlaceOnTitle();

        // Loose ash caught in whatever the box is doing to the air around it.
        _ashes = new AshSprite[AshCount];
        for (int i = 0; i < _ashes.Length; i++)
            _ashes[i] = new AshSprite { Center = Box.Position };
    }

    /// <summary>Loads the sky, the box and the ash.</summary>
    /// <param name="content">The content manager to load with.</param>
    public void LoadContent(ContentManager content)
    {
        foreach (AshDriftSprite layer in _ashDrift) layer.LoadContent(content);
        Box.LoadContent(content);
        foreach (AshSprite mote in _ashes) mote.LoadContent(content);
    }

    /// <summary>Puts the box back where the title screen has it: the whole picture, in the middle.</summary>
    public void PlaceOnTitle()
    {
        Box.Position = new Vector2(BlackBoxGame.ScreenWidth / 2f, TitleBoxY);
        Box.Scale = BlackBoxSprite.DrawScale;
    }

    /// <summary>Runs the sky, the box and the ash, every frame, whatever screen is up.</summary>
    /// <param name="gameTime">The frame's timing.</param>
    public override void Update(GameTime gameTime)
    {
        foreach (AshDriftSprite layer in _ashDrift) layer.Update(gameTime);
        Box.Update(gameTime, Game.GraphicsDevice.Viewport);

        // The ash follows the box wherever a screen has put it.
        foreach (AshSprite mote in _ashes)
        {
            mote.Center = Box.Position;
            mote.Update(gameTime);
        }

        base.Update(gameTime);
    }

    /// <summary>Draws the two layers of drifting ash behind everything. The point-sampled batch.</summary>
    /// <param name="gameTime">The frame's timing.</param>
    /// <param name="spriteBatch">The SpriteBatch to render with.</param>
    public void DrawSky(GameTime gameTime, SpriteBatch spriteBatch)
    {
        foreach (AshDriftSprite layer in _ashDrift)
            layer.Draw(gameTime, spriteBatch, Game.GraphicsDevice.Viewport);
    }

    /// <summary>Draws the loose ash spiralling into the mouth, in front of everything.</summary>
    /// <param name="gameTime">The frame's timing.</param>
    /// <param name="spriteBatch">The SpriteBatch to render with.</param>
    public void DrawAsh(GameTime gameTime, SpriteBatch spriteBatch)
    {
        foreach (AshSprite mote in _ashes) mote.Draw(gameTime, spriteBatch);
    }
}
